use_frameworks!

target 'IQChannels_Example' do
  platform :ios, '13.0'
  pod 'IQChannels', :git => 'git@github.com:iqstore/iqchannels-ios.git', :tag => '1.6.0'

  pod 'JSQMessagesViewController', :git => 'git@github.com:iqstore/JSQMessagesViewController.git', :tag => '7.3.10'

  target 'IQChannels_Tests' do
    inherit! :search_paths
  end
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
